Repository morph-data/morph, pull requests merged in 2025-03, with the labels that each got.

#140 Improve morph deploy: Prompt users to override environment variables
  core/morph/task/deploy.py
Labels: enhancement

#142 Enhancement/running func
  core/morph/api/custom_types.py
  core/morph/api/service.py
  core/morph/api/utils.py
  core/morph/config/project.py
  core/morph/task/resource.py
  core/morph/task/run.py
  core/morph/task/utils/morph.py
  core/morph/task/utils/run_backend/decorators.py
  core/morph/task/utils/run_backend/execution.py
  core/morph/task/utils/run_backend/inspection.py
  core/morph/task/utils/run_backend/output.py
  core/morph/task/utils/run_backend/state.py
Labels: enhancement

#141 Remove deprecated timezone manager functionality
  core/morph/task/api.py
  core/morph/task/run.py
  core/morph/task/utils/timezone.py
Labels: chore

#143 Fix run stream and write response in case of async function
  core/morph/task/utils/run_backend/output.py
Labels: bug

#144 Update version 0.2.0-rc2
  pyproject.toml
Labels: chore

#145 add uv as package manager
  core/morph/task/new.py
Labels: feature

#146 remove meta.json & result_ttl
  core/morph/api/app.py
  core/morph/api/service.py
  core/morph/config/project.py
  core/morph/include/Dockerfile
  core/morph/include/starter_template/morph_project.yml
  core/morph/task/compile.py
  core/morph/task/deploy.py
  core/morph/task/resource.py
  core/morph/task/run.py
  core/morph/task/utils/run_backend/cache.py
  core/morph/task/utils/run_backend/decorators.py
  core/morph/task/utils/run_backend/execution.py
  core/morph/task/utils/run_backend/inspection.py
  core/morph/task/utils/run_backend/state.py
  core/morph_lib/function.py
Labels: chore

#147 Fix uv package manager
  core/morph/task/deploy.py
  core/morph/task/new.py
Labels: bug

#149 Fix streaming error response
  core/morph/api/handler.py
  core/morph/api/service.py
Labels: bug

#150 make stream handle string
  core/morph/task/utils/run_backend/output.py
Labels: enhancement

#151 Fix update meta object value
  core/morph/task/run.py
  core/morph/task/utils/run_backend/execution.py
  core/morph/task/utils/run_backend/state.py
Labels: bug

#152 remove python and sql files from starter template
  core/morph/include/starter_template/data/Traffic_Orders_Demo_Data.csv
  core/morph/include/starter_template/src/pages/ai-app.mdx
  core/morph/include/starter_template/src/pages/data-app.mdx
  core/morph/include/starter_template/src/pages/index.mdx
  core/morph/include/starter_template/src/python/chat.py
  core/morph/include/starter_template/src/python/example.py
  core/morph/include/starter_template/src/sql/example_data.sql
  pyproject.toml
Labels: chore

#153 Update frontend package to 0.2.0
  core/morph/frontend/template/package.json
Labels: chore

#154 Fix dockerfile comment
  core/morph/include/Dockerfile
Labels: chore

#155 update version as v0.2.0
  pyproject.toml
Labels: chore

#158 Fix: Ensure poetry install and uv sync Runs Properly on morph new Task
  core/morph/include/starter_template/src/__init__.py
  core/morph/task/new.py
Labels: bug

#161 update version as v0.2.1
  pyproject.toml
Labels: chore

#164 Fix upload file endpoint cache path
  core/morph/api/service.py
Labels: bug

#165 Added deploy and build setting to morph_project.yml
  core/morph/api/cloud/client.py
  core/morph/config/project.py
  core/morph/task/deploy.py
  core/morph/task/new.py
Labels: feature

#163 Remove Dockerfile/.dockerignore generation on `morph new` command
  core/morph/include/Dockerfile
  core/morph/include/starter_template/.dockerignore
  core/morph/task/new.py
Labels: feature

#166 Fix file upload cache path
  core/morph/api/service.py
Labels: bug

#162 Feature/integrate @morph-data/frontend
  core/morph/api/app.py
  core/morph/api/templates/index.html
  core/morph/frontend/template/.eslintrc.cjs
  core/morph/frontend/template/.gitignore
  core/morph/frontend/template/index.html
  core/morph/frontend/template/package.json
  core/morph/frontend/template/src/admin/AdminPage.tsx
  core/morph/frontend/template/src/admin/common/useResourcesQuery.ts
  core/morph/frontend/template/src/admin/common/useScheduledJobsQuery.ts
  core/morph/frontend/template/src/admin/common/utils/useQuery.ts
  core/morph/frontend/template/src/admin/datapipeline/DataPipeline.tsx
  core/morph/frontend/template/src/admin/datapipeline/Flow.tsx
  core/morph/frontend/template/src/admin/datapipeline/ResourceDetail.tsx
  core/morph/frontend/template/src/admin/datapipeline/ResourceNode.tsx
  core/morph/frontend/template/src/assets/icons/database.svg
  core/morph/frontend/template/src/assets/icons/python.svg
  core/morph/frontend/template/src/error-page.tsx
  core/morph/frontend/template/src/main.tsx
  core/morph/frontend/template/src/mdx-componens.tsx
  core/morph/frontend/template/src/mdx.d.ts
  core/morph/frontend/template/src/page-skeleton.tsx
  core/morph/frontend/template/src/vite-env.d.ts
  core/morph/frontend/template/tsconfig.app.json
  core/morph/frontend/template/tsconfig.node.json
  core/morph/frontend/template/vite.config.ts
  core/morph/include/starter_template/components.json
  core/morph/include/starter_template/package.json
  core/morph/include/starter_template/src/pages/404.tsx
  core/morph/include/starter_template/src/pages/_app.tsx
  core/morph/include/starter_template/src/pages/_lib/utils.ts
  core/morph/include/starter_template/src/pages/_morph-data-lib/header.tsx
  core/morph/include/starter_template/src/pages/_morph-data-lib/index.ts
  core/morph/include/starter_template/src/pages/_morph-data-lib/root-error-boundary.tsx
  core/morph/include/starter_template/src/pages/_morph-data-lib/table-of-contents.tsx
  core/morph/include/starter_template/src/pages/index.css
  core/morph/include/starter_template/src/pages/index.mdx
  core/morph/include/starter_template/tsconfig.app.json
  core/morph/include/starter_template/tsconfig.json
  core/morph/include/starter_template/tsconfig.node.json
  core/morph/include/starter_template/vite.config.ts
  core/morph/task/api.py
  core/morph/task/deploy.py
  core/morph/task/new.py
  core/morph/task/utils/morph.py
Labels: feature

#167 chore: update @morph-data/frontend
  core/morph/include/starter_template/package.json
  core/morph/include/starter_template/src/pages/_app.tsx
  core/morph/task/api.py
Labels: feature

#168 update version as v0.3.0rc1
  pyproject.toml
Labels: chore

#169 Get dockerfile by calling api
  core/morph/task/deploy.py
  core/morph/task/utils/load_dockerfile.py
Labels: enhancement

#170 Feature/morph data frontend
  core/morph/include/starter_template/.gitignore
  core/morph/include/starter_template/src/pages/404.mdx
  core/morph/include/starter_template/src/pages/404.tsx
  core/morph/include/starter_template/src/pages/_app.tsx
  core/morph/include/starter_template/src/pages/_components/header.tsx
  core/morph/include/starter_template/src/pages/_components/table-of-contents.tsx
  core/morph/include/starter_template/src/pages/_morph-data-lib/index.ts
  core/morph/include/starter_template/src/pages/_morph-data-lib/root-error-boundary.tsx
  core/morph/include/starter_template/src/pages/index.mdx
  core/morph/include/starter_template/tsconfig.app.json
  core/morph/include/starter_template/tsconfig.json
  core/morph/include/starter_template/tsconfig.node.json
  core/morph/task/new.py
Labels: feature

#172 fix initial morph_project.yml
  core/morph/config/project.py
Labels: bug

#173 change dockerfile api call
  core/morph/config/project.py
  core/morph/task/deploy.py
  core/morph/task/utils/load_dockerfile.py
Labels: bug

#174 Issue v0.3.0rc2
  pyproject.toml
Labels: chore

#175 fix: 404.mdx → 404.tsx
  core/morph/include/starter_template/src/pages/404.mdx
  core/morph/include/starter_template/src/pages/404.tsx
Labels: feature

#177 change logic for checking use_custom_dockerfile
  core/morph/config/project.py
  core/morph/task/deploy.py
Labels: bug

#178 update version as v0.3.0rc3
  core/morph/task/utils/load_dockerfile.py
  pyproject.toml
Labels: chore

#179 update version as v0.3.0
  pyproject.toml
Labels: chore
