Repository morph-data/morph, pull requests merged in 2025-01, with the labels that each got.

#5 fix: run sql with connection on local
  core/morph/task/utils/run_backend/execution.py
Labels: bug

#7 Feature: morph version flag
  core/morph/cli/main.py
  poetry.lock
Labels: enhancement, feature

#8 fix: run with sql connection
  core/morph/task/utils/connection.py
  core/morph_lib/database.py
Labels: bug

#15 Fix/cloud conditions
  core/morph/api/app.py
  core/morph/api/auth.py
  core/morph/api/cloud/client.py
  core/morph/api/cloud/utils.py
  core/morph/cli/flags.py
  core/morph/cli/main.py
  core/morph/cli/params.py
  core/morph/config/project.py
  core/morph/include/starter_template/morph_project.yml
  core/morph/task/api.py
  core/morph/task/build.py
  core/morph/task/config.py
  core/morph/task/new.py
  core/morph/task/run.py
  core/morph/task/test.py
  core/morph/task/utils/connections/connector.py
  core/morph/task/utils/run_backend/execution.py
  core/morph_lib/api.py
  core/morph_lib/database.py
Labels: bug

#12 Fix: remove utils/file_upload.py from stater_template
  core/morph/api/service.py
  core/morph/include/starter_template/src/utils/file_upload.py
Labels: refactor

#13 Fix/readme quick start
  README.md
Labels: bug

#14 add contribution guide
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
  README.md
Labels: documentation, chore, feature

#16 fix: get saas token
  core/morph/task/utils/connection.py
  core/morph_lib/api.py
Labels: bug

#17 Refactor/remove unused commands
  core/morph/api/handler.py
  core/morph/api/service.py
  core/morph/api/types.py
  core/morph/cli/main.py
  core/morph/task/create.py
Labels: refactor

#19 fix: run frontend project in local .morph/frontend directory
  core/morph/api/app.py
  core/morph/api/templates/development/.gitkeep
  core/morph/api/templates/index.html
  core/morph/cli/main.py
  core/morph/cli/params.py
  core/morph/frontend/README.md
  core/morph/frontend/constants-base.js
  core/morph/frontend/constants.d.ts
  core/morph/frontend/index.html
  core/morph/frontend/package-lock.json
  core/morph/frontend/pre-build.js
  core/morph/frontend/public/vite.svg
  core/morph/frontend/src/assets/react.svg
  core/morph/frontend/src/custom-mdx-components.tsx
  core/morph/frontend/src/index.css
  core/morph/frontend/src/main-prod.tsx
  core/morph/frontend/src/pages/.gitkeep
  core/morph/frontend/template/.eslintrc.cjs
  core/morph/frontend/template/.gitignore
  core/morph/frontend/template/index.html
  core/morph/frontend/template/package.json
  core/morph/frontend/template/src/App.css
  core/morph/frontend/template/src/custom-mdx-components.tsx
  core/morph/frontend/template/src/error-page.tsx
  core/morph/frontend/template/src/main.tsx
  core/morph/frontend/template/src/mdx.d.ts
  core/morph/frontend/template/src/page-skeleton.tsx
  core/morph/frontend/template/src/vite-env.d.ts
  core/morph/frontend/template/tsconfig.app.json
  core/morph/frontend/template/tsconfig.json
  core/morph/frontend/template/tsconfig.node.json
  core/morph/frontend/template/vite.config.ts
  core/morph/frontend/yarn.lock
  core/morph/include/starter_template/package.json
  core/morph/task/api.py
  core/morph/task/clean.py
Labels: bug

#20 chore: add node_modules to .gitignore for morph new command
  core/morph/include/starter_template/.gitignore
Labels: chore

#22 Fix/serve command
  core/morph/api/app.py
  core/morph/cli/main.py
  core/morph/frontend/template/package.json
  core/morph/frontend/template/vite.config.ts
  core/morph/task/api.py
  core/morph/task/server.py
  poetry.lock
  pyproject.toml
Labels: bug

#23 fix: unused cli params & file extensions
  README.md
  core/morph/api/service.py
  core/morph/api/utils.py
  core/morph/cli/params.py
  core/morph/constants.py
  core/morph/task/utils/run_backend/inspection.py
  core/morph/task/utils/run_backend/state.py
Labels: chore

#24 Add user info to context.user_info and set mock data for local authorization tokens
  core/morph/api/auth.py
  core/morph/api/cloud/types.py
  core/morph/api/error.py
Labels: feature

#27 Replace @use-morph/page with @use-morph/components
  core/morph/api/app.py
  core/morph/frontend/template/package.json
  core/morph/frontend/template/src/custom-mdx-components.tsx
  core/morph/frontend/template/src/error-page.tsx
  core/morph/frontend/template/src/main.tsx
  core/morph/frontend/template/src/page-skeleton.tsx
  core/morph/frontend/template/vite.config.ts
Labels: feature

#28 chore: bump @use-morph/components
  core/morph/frontend/template/package.json
  core/morph/frontend/template/src/custom-mdx-components.tsx
Labels: chore

#29 fix: start server script
  core/morph/task/server.py
Labels: bug

#31 Optimize morph serve Command with Caching and DataFrame Previews
  .pre-commit-config.yaml
  core/morph/api/service.py
  core/morph/config/project.py
  core/morph/constants.py
  core/morph/include/starter_template/.gitignore
  core/morph/include/starter_template/morph_project.yml
  core/morph/task/clean.py
  core/morph/task/new.py
  core/morph/task/resource.py
  core/morph/task/run.py
  core/morph/task/utils/logging.py
  core/morph/task/utils/run_backend/cache.py
  core/morph/task/utils/run_backend/decorators.py
  core/morph/task/utils/run_backend/execution.py
  core/morph/task/utils/run_backend/inspection.py
  core/morph/task/utils/run_backend/output.py
  core/morph/task/utils/run_backend/types.py
  core/morph/task/utils/sqlite.py
  poetry.lock
  pyproject.toml
Labels: optimization

#32 Deprecate and Remove the morph sync Command
  core/morph/cli/main.py
  core/morph/task/sync.py
Labels: refactor

#33 Implement New morph deploy Command
  core/morph/api/cloud/base.py
  core/morph/api/cloud/client.py
  core/morph/cli/main.py
  core/morph/cli/params.py
  core/morph/config/project.py
  core/morph/include/Dockerfile.pip
  core/morph/include/Dockerfile.poetry
  core/morph/task/deploy.py
  core/morph/task/new.py
  core/morph/task/utils/file_upload.py
Labels: feature

#36 Chore: Clean Deprecated Template
  core/morph/include/Dockerfile.pip
  core/morph/include/Dockerfile.poetry
  core/morph/task/new.py
Labels: chore

#37 Enable poetry Interpreter in morph new Command
  core/morph/task/new.py
Labels: enhancement

#38 Remove Scheduled Jobs Functionalities
  core/morph/api/handler.py
  core/morph/api/service.py
  core/morph/config/project.py
  core/morph/include/starter_template/morph_project.yml
  core/morph/task/init.py
  core/morph/task/utils/knowledge/compile.py
  core/morph/task/utils/knowledge/find.py
  core/morph/task/utils/knowledge/inspection.py
  core/morph/task/utils/knowledge/state.py
  core/morph/task/utils/run_backend/decorators.py
  core/morph/task/utils/run_backend/state.py
  core/morph/task/utils/template/__init__.py
  core/morph/task/utils/template/inspection.py
  core/morph/task/utils/template/scaffold/config.json
  core/morph/task/utils/template/scaffold/json/vg_json_template.vg.json
  core/morph/task/utils/template/scaffold/mdx/mdx_starter_template.mdx
  core/morph/task/utils/template/scaffold/python/api.py
  core/morph/task/utils/template/scaffold/python/execute_sql.py
  core/morph/task/utils/template/scaffold/python/load_data_from_result.py
  core/morph/task/utils/template/scaffold/python/python_starter_template.py
  core/morph/task/utils/template/scaffold/python/visualization_matplotlib.py
  core/morph/task/utils/template/scaffold/python/visualization_plotly.py
  core/morph/task/utils/template/scaffold/sql/calc_sum_field_name.sql
  core/morph/task/utils/template/scaffold/sql/calc_sum_more_than_100.sql
  core/morph/task/utils/template/scaffold/sql/count_records.sql
  core/morph/task/utils/template/scaffold/sql/count_records_by_field_name.sql
  core/morph/task/utils/template/scaffold/sql/query_table.sql
  core/morph/task/utils/template/scaffold/sql/sql_empty_template.sql
  core/morph/task/utils/template/scaffold/sql/sql_starter_template.sql
  poetry.lock
Labels: refactor

#40 Configure environment variables before deployment
  core/morph/task/deploy.py
Labels: bug

#39 feat: admin page
  core/morph/api/app.py
  core/morph/frontend/template/package.json
  core/morph/frontend/template/src/App.css
  core/morph/frontend/template/src/admin/AdminPage.tsx
  core/morph/frontend/template/src/admin/common/useResourcesQuery.ts
  core/morph/frontend/template/src/admin/common/useScheduledJobsQuery.ts
  core/morph/frontend/template/src/admin/common/utils/useQuery.ts
  core/morph/frontend/template/src/admin/datapipeline/DataPipeline.tsx
  core/morph/frontend/template/src/admin/datapipeline/Flow.tsx
  core/morph/frontend/template/src/admin/datapipeline/ResourceDetail.tsx
  core/morph/frontend/template/src/admin/datapipeline/ResourceNode.tsx
  core/morph/frontend/template/src/assets/icons/database.svg
  core/morph/frontend/template/src/assets/icons/python.svg
  core/morph/frontend/template/src/main.tsx
  core/morph/frontend/template/src/page-skeleton.tsx
Labels: feature

#41 Format snowflake account identifier
  core/morph/task/utils/connections/snowflake/api.py
Labels: bug

#42 Fix Frontend Directory Lifecycle
  core/morph/constants.py
  core/morph/task/api.py
  core/morph/task/clean.py
  core/morph/task/deploy.py
  core/morph/task/new.py
  core/morph/task/utils/morph.py
Labels: bug

#43 chore: change starter template
  core/morph/include/Dockerfile
  core/morph/include/starter_template/.env
  core/morph/include/starter_template/src/example.csv
  core/morph/include/starter_template/src/sql/example_data.sql
Labels: chore

#44 Add timezone to postgresql connection
  core/morph/task/utils/connection.py
  core/morph/task/utils/connections/database/postgres.py
Labels: enhancement

#47 Fix Dockerfile Template
  core/morph/include/Dockerfile
Labels: bug

#46 refactor: remove sheduled jobs UI
  core/morph/frontend/template/src/admin/datapipeline/ResourceDetail.tsx
Labels: refactor

#48 feat: add defineState API
  core/morph/frontend/template/package.json
  core/morph/frontend/template/src/custom-mdx-components.tsx
  core/morph/frontend/template/src/main.tsx
  core/morph/frontend/template/src/page-skeleton.tsx
  core/morph/frontend/template/vite.config.ts
Labels: feature

#49 refactor: starter template
  core/morph/include/Dockerfile
  core/morph/include/starter_template/data/example.csv
  core/morph/include/starter_template/src/sql/example_data.sql
Labels: chore

#50 Removed serve preview option
  core/morph/cli/main.py
  core/morph/cli/params.py
  core/morph/task/api.py
Labels: chore

#51 Removed deprecated params from morph meta object
  core/morph/task/utils/run_backend/execution.py
Labels: bug

#52 update version=0.1.0
  pyproject.toml
Labels: chore

#57 fix: loosen tsconfig.json
  core/morph/frontend/template/tsconfig.app.json
Labels: bug

#60 update version v0.1.1
  pyproject.toml
Labels: chore

#63 fix: remove project id validation for morph config
  core/morph/api/cloud/client.py
  core/morph/task/deploy.py
Labels: bug

#66 Bug fix transform parquet output error handling
  core/morph/task/utils/run_backend/output.py
Labels: bug

#65 Add new feature morph context command
  core/morph/api/cloud/client.py
  core/morph/cli/main.py
  core/morph/cli/params.py
  core/morph/task/context.py
Labels: feature

#67 UserInfo to snake case at morph context command
  core/morph/api/cloud/types.py
  core/morph/task/context.py
Labels: bug

#68 Add Warning and Confirmation Prompt Before Overwriting Existing Profiles
  core/morph/task/config.py
Labels: feature

#69 Add title auto detection and table of contents floater to MDX pages
  core/morph/frontend/template/package.json
  core/morph/frontend/template/src/custom-mdx-components.tsx
  core/morph/frontend/template/src/main.tsx
  core/morph/frontend/template/src/page-skeleton.tsx
  core/morph/frontend/template/vite.config.ts
Labels: feature

#70 fix: Force light mode to prevent unintended dark mode in hosted envir…
  core/morph/api/templates/index.html
Labels: bug

#71 add stream_chat for simple usage
  core/morph_lib/stream.py
Labels: enhancement

#64 Add Python Version Selection to morph new Command
  core/morph/include/Dockerfile
  core/morph/task/api.py
  core/morph/task/new.py
  core/morph/task/run.py
  core/morph/task/utils/timezone.py
  poetry.lock
  pyproject.toml
Labels: feature

#72 Update starter template
  core/morph/include/starter_template/data/Traffic_Orders_Demo_Data.csv
  core/morph/include/starter_template/data/example.csv
  core/morph/include/starter_template/src/pages/index.mdx
  core/morph/include/starter_template/src/pages/sql_agent.mdx
  core/morph/include/starter_template/src/python/example.py
  core/morph/include/starter_template/src/python/sql_agent.py
  core/morph/include/starter_template/src/sql/example_data.sql
Labels: enhancement

#73 Enable --force Flag to Clean .morph/frontend directory in morph clean Command
  core/morph/cli/main.py
  core/morph/cli/params.py
  core/morph/task/clean.py
Labels: feature

#75 add error handling for missing OPENAI_API_KEY when using chat template
  core/morph/include/starter_template/src/python/sql_agent.py
Labels: enhancement

#74 Fix: Page title fallback on its header
  core/morph/frontend/template/src/main.tsx
Labels: bug
