Repository morph-data/morph, pull requests merged in 2025-02, with the labels that each got.

#79 Fixed to work even if morph_project.yml is not present when morph config command is executed
  core/morph/api/cloud/client.py
Labels: bug

#81 add mock_user_context.json to stater_template
  core/morph/include/starter_template/.mock_user_context.json
Labels: chore

#80 Correct pyproject.toml Generation in morph new Command for Poetry Projects
  core/morph/task/new.py
Labels: bug

#82 Fix convert invalid dataframe type
  core/morph/api/utils.py
Labels: bug

#83 Load project profile instead of default
  core/morph/task/api.py
  core/morph/task/run.py
Labels: bug

#84 Update: @morph-data/components@0.1.3
  core/morph/frontend/template/package.json
  core/morph/frontend/template/src/custom-mdx-components.tsx
  core/morph/frontend/template/vite.config.ts
Labels: chore

#85 update version as v0.1.3
  pyproject.toml
Labels: chore

#88 hotfix: pyproject.toml initialization
  core/morph/task/new.py
  pyproject.toml
Labels: bug

#91 Maintenance: remove ai lib functions
  core/morph/include/starter_template/src/pages/sql_agent.mdx
  core/morph/include/starter_template/src/python/sql_agent.py
  core/morph_lib/ai/anthropic/code_generation.py
  core/morph_lib/ai/anthropic/model.py
  core/morph_lib/ai/azure/code_generation.py
  core/morph_lib/ai/azure/model.py
  core/morph_lib/ai/common/code_generation.py
  core/morph_lib/ai/common/prompt.py
  core/morph_lib/ai/common/types.py
  core/morph_lib/ai/groq/code_generation.py
  core/morph_lib/ai/groq/model.py
  core/morph_lib/ai/openai/code_generation.py
  core/morph_lib/ai/openai/model.py
  poetry.lock
  pyproject.toml
Labels: chore

#93 Update version as v0.1.5
  pyproject.toml
Labels: chore

#94 Update components package to v0.1.5
  core/morph/frontend/template/package.json
Labels: chore

#95 Fix morph serve API - Invalid Cache Handling at File Upload Endpoint
  core/morph/api/service.py
Labels: bug

#98 fix dependencies version
  pyproject.toml
Labels: bug

#99 Fix dependencies version range
  poetry.lock
  pyproject.toml
Labels: bug

#100 update version as v0.1.6
  pyproject.toml
Labels: chore

#103 feat: add auto configurations and custormizations of html metadata
  core/morph/api/app.py
  core/morph/frontend/template/package.json
  core/morph/frontend/template/src/main.tsx
  core/morph/include/Dockerfile
  core/morph/include/starter_template/static/favicon.ico
Labels: feature

#106 update version as v0.1.7
  pyproject.toml
Labels: chore

#107 fix: streaming response on cloud
  core/morph/api/app.py
  core/morph/api/custom_types.py
  core/morph/api/handler.py
  core/morph/api/service.py
Labels: bug

#108 update version as v0.1.8
  pyproject.toml
Labels: chore

#109 update starter template using new dockerfile
  core/morph/include/Dockerfile
  core/morph/include/starter_template/.dockerignore
Labels: chore

#114 remove unused package
  README.md
  core/morph/include/starter_template/src/python/example.py
  core/morph/task/utils/run_backend/execution.py
  core/morph/task/utils/run_backend/output.py
  core/morph_lib/__init__.py
  core/morph_lib/types.py
  poetry.lock
  pyproject.toml
Labels: chore

#113 update version & readme
  README.md
  pyproject.toml
Labels: chore

#116 Fix/morph data components data api
  core/morph/frontend/template/package.json
Labels: bug

#117 Enhancement/remove fig coversion
  .pre-commit-config.yaml
  core/morph/include/starter_template/src/pages/ai-app.mdx
  core/morph/include/starter_template/src/pages/data-app.mdx
  core/morph/include/starter_template/src/pages/index.mdx
  core/morph/include/starter_template/src/python/chat.py
  core/morph/include/starter_template/src/sql/example_data.sql
  core/morph/task/utils/run_backend/decorators.py
  core/morph/task/utils/run_backend/output.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#118 replace demo image with gif
  README.md
Labels: chore

#119 bump @morph-data/components
  core/morph/frontend/template/package.json
Labels: bug

#120 fix duckdb execution when running morph serve
  core/morph/include/starter_template/src/sql/example_data.sql
  core/morph/task/utils/connections/connector.py
Labels: bug

#121 bump @morph-data/components
  core/morph/frontend/template/package.json
Labels: bug

#122 remove pil dependency
  core/morph/api/custom_types.py
  core/morph/api/handler.py
  core/morph/api/service.py
  core/morph/api/utils.py
  core/morph/task/utils/run_backend/execution.py
Labels: bug

#136 print detailed log every time server restarts
  core/morph/api/app.py
  core/morph/api/error.py
  core/morph/task/api.py
  core/morph/task/server.py
  core/morph/task/utils/run_backend/errors.py
  core/morph/task/utils/run_backend/inspection.py
  core/morph_lib/api.py
  core/morph_lib/database.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#132 remove title from @morph.func params
  core/morph/task/utils/run_backend/decorators.py
Labels: chore

#135 Add plugin command
  core/morph/__init__.py
  core/morph/api/app.py
  core/morph/api/plugin.py
  core/morph/cli/main.py
  core/morph/constants.py
  core/morph/frontend/template/src/custom-mdx-components.tsx
  core/morph/frontend/template/src/main.tsx
  core/morph/frontend/template/src/mdx-componens.tsx
  core/morph/task/plugin.py
  core/morph_lib/function.py
Labels: feature

#137 update version as v0.2.0rc1
  pyproject.toml
Labels: chore
